# Generated by Django 3.2.20 on 2023-08-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TXT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
